name: arab_wordle_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/words/5_letters/5_letter_words_all.json
    - assets/words/5_letters/5_letter_answers.json
    - assets/words/4_letters/4_letter_words_all.json
    - assets/words/4_letters/4_letter_answers.json
    - assets/words/3_letters/3_letter_words_all.json
    - assets/words/3_letters/3_letter_answers.json
    - assets/images/Mountains.png
